Add a way to configure the upload directory
uclouvain/osis-document pull request #30
Opened 2022-01-17 08:44 UTC by jcougnaud

Related to https://github.com/uclouvain/osis-document/issues/12

2022-01-17 14:26 UTC, SebCorbin requested changes

2022-01-17 14:26 UTC, SebCorbin commented on frontend/components/ViewEntry.test.js
> +     it('if the fullname has no extension', async () => {
- indentation
 - `it()` est bien si tu donne un nom de test comme _should work with ..._, dans ton cas, utilise plutôt `test()`, ça rend le code un poil plus lisible

2022-01-17 14:26 UTC, SebCorbin commented on osis_document/api/serializers.py
> +                    'Impossible to found one single object on which to compute the upload directory path',
```suggestion
                    'Impossible to find a single object on which to compute the upload directory path',
```

2022-01-17 14:26 UTC, SebCorbin commented on osis_document/api/serializers.py
> +            except (content_type.model_class().DoesNotExist, content_type.model_class().MultipleObjectsReturned):
Tu as pas mal d'utilisations de `content_type.model_class()`, à mettre dans une variable `model`

2022-01-17 14:26 UTC, SebCorbin commented on schema.yml
> +              $ref: '#/components/schemas/ConfirmUploadRequest'
Tu ne devrais pas avoir ces changement de content type en entrée, retire-les à la main pour le moment

2022-01-17 16:28 UTC, jcougnaud commented on schema.yml
> +              $ref: '#/components/schemas/ConfirmUploadRequest'
Ça marche merci, je supprime ça.

2022-01-17 16:32 UTC, SebCorbin approved these changes

2022-01-18 08:02 UTC, albrugnetti approved these changes

2022-01-18 08:02 UTC, merged