[OSIS-7970] Asynchone post processing
uclouvain/osis-document pull request #75
Opened 2023-06-01 15:01 UTC by vbrichant

2023-06-01 15:01 UTC, sips-uclouvain commented
Can one of the admins verify this patch?

2023-06-05 09:45 UTC, BenJneB commented on osis_document/api/views/token.py
> +        data = []
```python3
data = []
for upload in uploads:
   post_processing_check = self.check_post_processing(
      request=request,
      upload=upload,
      request.data.get('post_process_type')
   )
   status = post_processing_check.get('status')
   if status == PostProcessingStatus.PENDING.name:
      return Response(
         data=post_processing_check,
         status=status.HTTP_206_PARTIAL_CONTENT,
         headers=self.get_success_headers(data=None),
      )
   elif status == PostProcessingStatus.FAILED.name:
      return Response(
         data=post_processing_check,
         status=status.HTTP_500_INTERNAL_SERVER_ERROR,
         headers=self.get_success_headers(data=None),
      )

   if upload.status == FileStatus.INFECTED.name:
      results[str(upload.pk)] = {'error': DocumentError.get_dict_error(DocumentError.INFECTED.name)}
   elif post_processing_check:
      post_process_data = post_processing_data.get('data', [])
      data.append(iter(post_process_data))
   else:
      data.append({'upload_id': upload.pk, 'access': self.token_access})
   
```

2023-06-05 11:52 UTC, vbrichant commented on osis_document/tasks.py
> +                post_process_async.status = PostProcessingStatus.FAILED.name
Pour moi ça n'a pas de sens étant donné que c'est une vérification du bon déroulement du processus.
Si je suit ta logique, je suis obligé de mettre le statut du post processing a DONE à chaque actions, ce qui l'enpêche d'être en PENDING dans le cas ou l'user tenterais d'accéder au résultat pendant l'exécution du post processing

2023-06-05 12:18 UTC, vbrichant commented on osis_document/api/views/token.py
> +        data = []
c'est voulu de ne pas avoir nommé le paramètre wanted_post_process dans l’appel de la fonction check_post_processing ? (6ème ligne)

2023-06-19 12:56 UTC, albrugnetti requested changes

2023-06-19 12:56 UTC, albrugnetti commented on README.md
> +        async_post_processing=Flase,
False*

2023-06-19 12:56 UTC, albrugnetti commented on osis_document/api/views/post_processing.py
> +                }
Pourquoi ne pas faire simplement
```python
...
 data=self.request.data 
...

2023-06-19 12:56 UTC, albrugnetti commented on osis_document/api/utils.py
> +def get_remote_token(uuid, write_token=False, type_post_processing=None):
Hésite pas à mettre à jour le  commentaire pour expliquer le but de la variable type_post_processing

2023-06-19 12:56 UTC, albrugnetti commented on osis_document/tasks.py
> +                intermediary_uuids_list = output_data[action]['output']['upload_objects']
Pourquoi utiliser deux variables **base_uuids_list** et **intermediary_uuids_list** ? 

Est-ce que c'est pas plus simple d'avoir une variable nommée:  **current_processing_uuids = []** que tu vas modifier au fur et à mesure en fonction du postprocessing ?

2023-06-19 12:56 UTC, albrugnetti commented on osis_document/tasks.py
> +                    }
Pourquoi il y a deux moyens de catcher les erreurs? Est-ce qu'il ne faut pas avoir plusieurs niveau except (Spécifique au générique). Ex:
```python
try: 
   ... <Code qui va raiser des exceptions>
except SpecificException as e:
    post_process_async.results[action]['errors'] = {
          'messages': e.messages,
          'params': str(e.params['value'])
      }
except Exception as e:
      post_process_async.results[action]['errors'] = {
           'messages': e.args or e.default_detail
      }

2023-06-19 12:56 UTC, albrugnetti commented on osis_document/tasks.py
> +                post_process_async.status = PostProcessingStatus.FAILED.name
Tu peux utiliser la fonction any() en python pour voir si il y a un postprocessing failed alors, on a failed sinon done.
```python
has_postprocessing_errors = any([p['status'] == PostProcessingStatus.FAILED.name for p in ....])

2023-06-29 14:49 UTC, BenJneB commented on osis_document/api/serializers.py
> +    pk = serializers.UUIDField(
uuid ?

2023-06-29 14:51 UTC, BenJneB commented on osis_document/api/serializers.py
> +class GetProgressAsyncPostProcessingSerializer(serializers.Serializer):
ProgressAsyncPostProcessingSerializer

2023-06-29 14:56 UTC, BenJneB commented on osis_document/api/views/post_processing.py
> +        'POST': (None, serializers.GetProgressAsyncPostProcessingSerializer),
Je pense que c'est plutot (serializers.GetProgressAsyncPostProcessingSerializer, None)
(entrée, sortie)

N'y aurait-il pas une sortie d'aillerus ?

2023-06-30 09:31 UTC, BenJneB commented on osis_document/api/utils.py
> +    if isinstance(tokens, Dict):
C'est pourquoi ces if return ?

2023-06-30 09:39 UTC, BenJneB commented on osis_document/api/views/token.py
> +    ) -> Dict[str, str or Dict[str, str]] or None:
Optional[Dict[str, Union[str, Dict[str, str]]

2023-06-30 09:40 UTC, BenJneB commented on osis_document/api/views/token.py
> +    ) -> Dict[str, str or Dict[str, str]]:
idem

2023-06-30 09:40 UTC, BenJneB commented on osis_document/api/views/token.py
> +            async_qs: QuerySet,
Tu peux préciser : QuerySet[PostProcessAsync]

2023-06-30 10:01 UTC, BenJneB commented on osis_document/api/views/token.py
> +        post_processing_list = PostProcessing.objects.filter(uuid__in=async_result['post_processing_objects'])
Tu peux pas directement récuperer ce qu'il te faut? (et éviter la boucle for)

```python3
post_processing_list = PostProcessing.objects.filter(
   uuid__in=async_result['post_processing_objects'],
   input_files=upload
)
if post_processing_list.exists():
   return post_processing_list.get().output_files.first().uuid
```

2023-06-30 10:09 UTC, BenJneB commented on osis_document/tests/factories.py
> +            "base_input": [*base_input],
tu peux juste mettre "base_input": base_input

2023-07-10 06:56 UTC, vbrichant commented on osis_document/api/views/post_processing.py
> +        'POST': (None, serializers.GetProgressAsyncPostProcessingSerializer),
Il n'y en a aucune,car pour moi le validated_data n'est pas considéré comme un retour

2023-07-10 08:32 UTC, vbrichant commented on osis_document/api/utils.py
> +    if isinstance(tokens, Dict):
Je ne sais plus pourquoi j'ai ajouter cela, et je n'en vois pas la raison, je les ai donc supprimé

2023-07-11 14:41 UTC, albrugnetti requested changes

2023-07-11 14:41 UTC, albrugnetti commented on osis_document/api/views/token.py
> +                request.data['expires_at'] = now() + timedelta(seconds=self.request.data.get('custom_ttl'))
Vu que tu as vérifié l'existance de la propriété custom_ttl, tu peux faire un accès direct self.request.data['custom_ttl']

2023-07-11 14:41 UTC, albrugnetti commented on osis_document/api/views/token.py
> +                token_data.update({'expires_at': now() + timedelta(seconds=self.request.data.get('custom_ttl'))})
Idem + sortir la fonction now() afin d'éviter d'avoir des validités différentes

2023-07-13 08:04 UTC, merged