[Osis-8242] add check progress of post-processing in component from VueJS
uclouvain/osis-document pull request #80
Opened 2023-07-25 13:02 UTC by vbrichant

2023-07-27 07:09 UTC, albrugnetti requested changes

2023-07-27 07:09 UTC, albrugnetti commented on frontend/components/ViewEntry.vue
> +          const url = this.baseUrl + (this.getProgressUrl.split('/').slice(3).join("/")) + '?' + 'pk=' + uuid.toString();
Pourquoi est-ce que tu dois faire autant de split/cast ?

2023-07-27 07:22 UTC, vbrichant commented on frontend/components/ViewEntry.vue
> +          const url = this.baseUrl + (this.getProgressUrl.split('/').slice(3).join("/")) + '?' + 'pk=' + uuid.toString();
Afin construire l'url de la requête API avec les information que je reçois, pour qu'elle soit valide. 
Je suis obligé d'extraire l'uuid de getProgressUrl afin de pouvoir les mettre en tant que queryParams ce qui est nécessaire car on utilise self.request.get('uuid') coté API.
Et aussi parce qu'il y a des partie des string commune entre getProgressUrl et baseURL

2023-07-27 11:57 UTC, vbrichant commented on frontend/components/ViewEntry.vue
> +        if (this.value === 'None'){
C'était une erreur de ma part, l'API ne renvoie pas de 'None' mais c'était le template_tag qui retournais 'None'

2023-07-28 06:23 UTC, albrugnetti commented on osis_document/templates/osis_document/visualizer.html
> +     data-get-progress-url="{{get_progress_url}}"
Pourquoi est-ce que l'URL de la progression (**data-get-progress-url**) , le statut (**data-post-process-status**), l'UUID (**data-base-uuid**) doivent être fournies dans le composant ? 

Le client ne doit pas être conscient d'un post_processing ou pas, c'est bien au serveur de fournir les informations

2023-07-28 06:23 UTC, albrugnetti commented on osis_document/templatetags/osis_document.py
> +            }
Idem commentaire du haut

2023-07-28 06:44 UTC, vbrichant commented on osis_document/templates/osis_document/visualizer.html
> +     data-get-progress-url="{{get_progress_url}}"
Je ne suis pas sûr de te comprendre, pour moi, c'est bien le serveur qui donne l'information étant donné que c'est des informations provenant du get_remote_token effectué dans le template_tag

2023-07-28 06:46 UTC, vbrichant commented on osis_document/templates/osis_document/visualizer.html
> +     data-get-progress-url="{{get_progress_url}}"
Ou alors il me faut refaire un get_remote_token depuis le component, mais pour moi ça n'a pas de sens de le refaire une seconde fois

2023-07-28 07:09 UTC, albrugnetti commented on osis_document/templates/osis_document/visualizer.html
> +     data-get-progress-url="{{get_progress_url}}"
Effectivement, si on passe uniquement via le templatetag. 
Néanmoins, il faudra revoir l'approche lorsqu'on utilisera plus le templatetag mais directement le composant document-visualizer de vuejs.

2023-07-28 07:09 UTC, albrugnetti approved these changes

2023-07-28 07:14 UTC, merged