Add schema and revamp with managers
uclouvain/osis-document pull request #9
Opened 2021-06-10 15:23 UTC by SebCorbin

2021-06-11 13:50 UTC, albrugnetti requested changes

2021-06-11 14:22 UTC, SebCorbin commented on schema.yml
> +  version: '1.11'
J'avoue j'ai fait un gros copié-collé d'internship :p

2021-06-11 14:23 UTC, SebCorbin commented on schema.yml
> +  - Token: []
Alors ouais, je pense que c'est faisable, mais faudrait standardiser ça, je me suis inspiré d'internship qui expose un SDK aussi, comment vous faites actuellement ?

2021-06-14 06:48 UTC, albrugnetti commented on schema.yml
> +  - Token: []
Au niveau du SDK d'internship, il s'agit d'un utilisateur qui effectue l'appel (On a besoin de 'personnifier' l'appel via le Token)
Dans le cas d'OSIS Document, il s'agit d'une d'appel server-to-serveur dans lequel, nous n'avons pas besoin d'avoir l'identité de la personne car c'est bien la couche métier (ex. OSIS-Admission) qui va vérifier les permissions. Nous devons simplement nous assurer que l'application OSIS-Admission a bien les accès vers OSIS-Document pour pouvoir effectuer les appels (+ restriction IP/reseau au niveau infra)

2021-06-14 12:10 UTC, albrugnetti approved these changes

2021-06-14 12:10 UTC, merged